### ISSUE TITLE
Follower goal not reading follower amount properly.

### ISSUE THREAD

**Issue by JustJakee** [Casterlabs/Koi#13]
### Follower Goal Bar is not picking up correct amount of followers for caffeine streamer. 

**Screenshots Below**
_____________

| | | |
|:-------------------------:|:-------------------------:|:-------------------------:|
|<img width="1604" alt="screen shot 2017-08-07 at 12 18 15 pm" src="https://user-images.githubusercontent.com/45543899/93408429-1cabfd00-f85a-11ea-920b-0c6bda65dd37.PNG">  blah |  |<img width="1604" alt="screen shot 2017-08-07 at 12 18 15 pm" src="https://user-images.githubusercontent.com/45543899/93408452-33525400-f85a-11ea-9031-9d7993395a6e.PNG">|

**Comment by e3ndr** [comment]
Seems to have been related to Caffeine's API maintenance yesterday. Marking as wontfix until the issue comes up again.
